### ISSUE TITLE
TestScoped doesn't work in non-test thread.

### ISSUE THREAD

**Issue by LiaWind** [google/acai#7]
When start a thread from the test, it can't inject `@TestScoped` instance to the new thread.
It throws `com.google.inject.OutOfScopeException: Attempt to inject @TestScoped binding outside test:`

**Comment by nlativy** [comment]
This is a known limitation. You need to inject fields into the test and then pass them on to the relevant thread.

Could you provide more information about the use case?

One thing we could potentially do is provide a static method like `TestScopes.continueTest` that wraps a `Callable<T>` so it can get access to the test scope. Then if you need to do something on another thread in the test it could work:

```java
@RunWith(JUnit4.class)
public class MyTest {
  @Rule public Acai acai = new Acai(TestModule.class);
  private final ExecutorService service = Executors.newCachedThreadPool();
  @Inject private Provider<TestHelper> testHelperProvider;

  @Test
  public void injectValueInDifferentThread() {
    service.submit(TestScopes.continueTest(new Callable<Void>() {
      @Override public Void call() throws Exception {
        // continueTest would wrap the callable making get on the provider
        // work here.
        TestHelper myHelper = testHelperProvider.get();
        // ... useful stuff goes here ...
        return null;
      }
    }));
  }
}
```

Would that help?

Would be good to understand the use case more to help decide if it should be supported and the best way to do so. In general we would expect `@TestScoped` to be used only for test objects and injected into the test itself and passed down. I would expect the production code to be more likely to do stuff on threads but wouldn't use `@TestScoped` there.

**Comment by nlativy** [comment]
This is fixed for threads started from the test thread in commit #23.
